### ISSUE TITLE
Break statement

### ISSUE THREAD

**Issue by RioFairhall** [I-am-python/Basic-C-codes#1]
void main()
{
    
    while (1)
    {
        main_prog();
        char request;
        printf("Enter \'y\' to continue and \'n\' to exit: ");
        scanf(" %c",&request);
        if (request == 'y' || request == 'Y' )
        {
            continue;
        }
        else if (request == 'n' || request == 'N')
        {
            break;
        }
        break; /*we don't need to add this break statement here, cause in else if there already a break statement is defined which would be sufficient to end the loop.*/
/*Although it's a precaution used here, if something goes wrong, it end the loop. */
    }
}

**Comment by RioFairhall** [comment]
It's just for explanation, why he used break statement there. 
*it's not a issue*

**Comment by I-am-python** [comment]
> It's just for explanation, why he used break statement there.
> _it's not a issue_

thanks buddy for your explanaition!
